import sys

# source: https://de.wikipedia.org/wiki/Fahrzeug-Identifizierungsnummer
dct_wmi = {
    "JMB" : "Mitsubishi", 
    "JMZ" : "Mazda", 
    "KMH" : "Hyundai (Korea)", 
    "KNE" : "Kia (Montage nicht Korea)", 
    "KPT" : "Ssangyong", 
    "LFV" : "FAW-Volkswagen Automotive Co.", 
    "SAJ" : "Jaguar", 
    "SAL" : "Land Rover", 
    "SAR" : "Rover", 
    "SCC" : "Lotus Cars", 
    "SUU" : "Solaris Bus & Coach", 
    "TMA" : "Hyundai (Tschechien)", 
    "TMB" : "Škoda", 
    "TRU" : "Audi (Ungarn)", 
    "U5Y" : "Kia (Slowakei, Pkw)", 
    "U6Z" : "Kia (Slowakei, SUV)", 
    "VA0" : "ÖAF Gräf & Stift AG (Österreich)", 
    "VFA" : "Alpine, heute Renault", 
    "VF1" : "Renault", 
    "VF3" : "Peugeot", 
    "VF7" : "Citroën", 
    "VNK" : "Toyota Frankreich", 
    "VSK" : "Nissan Spanien", 
    "VSS" : "Seat", 
    "WAG" : "Neoplan", 
    "WAU" : "Audi", 
    "WAP" : "ALPINA", 
    "WBA" : "BMW", 
    "WBS" : "BMW M GmbH", 
    "WBY" : "BMW i (Elektro)", 
    "WDB" : "Mercedes-Benz", 
    "WDC" : "DaimlerChrysler/Daimler AG", 
    "WDD" : "DaimlerChrysler/Daimler AG", 
    "WDF" : "DaimlerChrysler/Daimler AG", 
    "WMX" : "DaimlerChrysler/Daimler AG", 
    "WEB" : "EvoBus", 
    "WF0" : "Ford Deutschland", 
    "WGF" : "GFB GmbH", 
    "WJR" : "Irmscher", 
    "WKA" : "Kaeser Kompressoren", 
    "WKK" : "Kässbohrer Fahrzeugwerke", 
    "WLA" : "Langendorf GmbH", 
    "WMA" : "MAN", 
    "WME" : "Smart", 
    "WMW" : "MINI", 
    "WP0" : "Porsche", 
    "WP1" : "Porsche Cayenne", 
    "WP1" : "Porsche Macan", 
    "WSM" : "Schmitz Cargobull", 
    "WUA" : "Audi Sport GmbH", 
    "WVG" : "Volkswagen", 
    "WVM" : "VW-MAN", 
    "WVW" : "Volkswagen", 
    "WV1" : "Volkswagen Nutzfahrzeuge", 
    "WV2" : "Volkswagen Nutzfahrzeuge", 
    "W0L" : "Opel", 
    "W0V" : "Vauxhall", 
    "W08" : "Saturn Astra", 
    "W09" : "deutsche Hersteller < 500 Fz.", 
    "YK1" : "Saab", 
    "YS3" : "Saab", 
    "YV1" : "Volvo Cars", 
    "ZAR" : "Alfa Romeo", 
    "ZCF" : "Iveco", 
    "ZDF" : "Ferrari Dino", 
    "ZFA" : "Fiat", 
    "ZFF" : "Ferrari", 
    "ZHW" : "Lamborghini", 
    "ZLA" : "Lancia", 
    "ZAM" : "Maserati", 
    "1G3" : "Oldsmobile", 
    "1GC" : "Chevrolet", 
    "1GM" : "Pontiac", 
    "1VW" : "Volkswagen USA", 
    "1YV" : "Mazda USA", 
    "2G1" : "Chevrolet Kanada", 
    "2G1" : "Pontiac Kanada", 
    "2HM" : "Hyundai Kanada", 
    "3VW" : "Volkswagen Mexiko", 
    "4US" : "BMW USA", 
    "5YJ" : "Tesla USA", 
    "6MM" : "Mitsubishi Motors Corporation Australien", 
    "6T1" : "Toyota Australien", 
    "9BW" : "Volkswagen Brasilien"
}

def parseWmi(s_vin):
    s_vin = s_vin.upper()

    if len(s_vin) is not 17:
        print("[*] Invalid VIN. Length must be 17 but was {}.".format(len(s_vin)))
        sys.exit("[*] Exit program.")

    if s_vin[:3] in dct_wmi:
        print("[*] Manufacturer is {}.".format(dct_wmi[s_vin[:3]]))
    else:
        print("[*] Manufacturer not known.")